import data from "../data/activity.json";

/** Generated by scripts/fetch-activity.mjs before every build. */
export type LogEntry = { date: string; product: string; message: string };
export type Product = {
  id: string;
  name: string;
  url: string;
  work: string;
  lastShipped: string | null;
  changes30d: number;
  status: { up: boolean; code: number; ms: number };
};

export const ACTIVITY = data as {
  generatedAt: string;
  checkedAt: string;
  streakWeeks: number;
  changes30d: number;
  products: Product[];
  log: LogEntry[];
};

export function productName(id: string) {
  return ACTIVITY.products.find((p) => p.id === id)?.name ?? id;
}

export function productWork(id: string) {
  return ACTIVITY.products.find((p) => p.id === id)?.work;
}

/** "5 Oct 2026" — fixed format so server and browser agree. */
export function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "Asia/Kathmandu" });
}

/** Log entries grouped by Kathmandu calendar day, newest first. */
export function byDay(entries: LogEntry[]) {
  const days = new Map<string, LogEntry[]>();
  for (const e of entries) {
    const key = new Date(e.date).toLocaleDateString("en-CA", { timeZone: "Asia/Kathmandu" });
    days.set(key, [...(days.get(key) ?? []), e]);
  }
  return [...days.entries()];
}
